BlogBundle\Entity\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        author:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: comments
            joinColumn:
                name: article_id
                referencedColumnName: id
                onDelete: CASCADE
